POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyYjk4NDcwZGYxYTYxN2ZjZmYwY2FjNyIsImlhdCI6MTY1NjgzNjI2NCwiZXhwIjoxNjU2ODM5ODY0fQ.1NCbPgI29EcNCe2Usj2NCCnQBaq-pOyMYGGCWso5LNY

{
  "title": "testing",
  "author": "roots",
  "url": "asdasd",
  "likes": 222
}